//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacione
    {
        public int id_asignacion { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_reparacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Reparacione Reparacione { get; set; }
    }
}
