//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repuestos_Categorias
    {
        public int id_repuesto_categoria { get; set; }
        public Nullable<int> id_repuesto { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual CategoriasRepuesto CategoriasRepuesto { get; set; }
        public virtual Repuesto Repuesto { get; set; }
    }
}
