//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int id_visita { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string descripcion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
